title: Heather Blackwood's Portfolio
#logo: /assets/img/logo.png
# description text bwlow image

# next line is if I allow othrs to download my code
# show_downloads: true
theme: jekyll-theme-cayman
#theme: Cayman
